apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sre-alert-agent-output
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: "${EKS_EFS_STORAGE_CLASS}"
